### PR TITLE
fix: don't panic if no reserve in ReserveLastBinIDs

### LINKED ISSUE #4270: debugstore panics on ultra-light node
### Context
1.18.2 bee node in ultra-light mode

### Summary
I attempted to do a /debugstore to the debug API port and the ultra-light bee node logged a panic.

### Expected behavior
I expected a valid answer from the API.

### Actual behavior
```
"msg"="http: panic serving 192.168.10.177:59572: runtime error: invalid memory address or nil pointer dereference
goroutine 137133 [running]:
net/http.(*conn).serve.func1()
	net/http/server.go:1854 +0xb0
panic({0xe07520, 0x1f00320})
	runtime/panic.go:890 +0x248
github.com/ethersphere/bee/pkg/storer/internal/reserve.(*Reserve).LastBinIDs(0x0?, {0xffff6f823b38?, 0x4001810480?})
	github.com/ethersphere/bee/pkg/storer/internal/reserve/reserve.go:474 +0x38
github.com/ethersphere/bee/pkg/storer.(*DB).ReserveLastBinIDs(0x40016221e0)
	github.com/ethersphere/bee/pkg/storer/reserve.go:406 +0x64
github.com/ethersphere/bee/pkg/storer.(*DB).DebugInfo(0x40016221e0, {0x157e170?, 0x400899cdb0?})
	github.com/ethersphere/bee/pkg/storer/debug.go:129 +0x35c
github.com/ethersphere/bee/pkg/api.(*Service).debugStorage(0x400001b500, {0x157d030, 0x4004a58b60}, 0x4004da3e00)
	github.com/ethersphere/bee/pkg/api/debugstorage.go:17 +0xe0
net/http.HandlerFunc.ServeHTTP(0x4003d37308?, {0x157d030?, 0x4004a58b60?}, 0x1c334?)
	net/http/server.go:2122 +0x38
github.com/ethersphere/bee/pkg/log/httpaccess.NewHTTPAccessSuppressLogHandler.func1.1({0x157ad20?, 0x40087bafa0?}, 0x4003d372f8?)
	github.com/ethersphere/bee/pkg/log/httpaccess/http_access.go:25 +0x58
net/http.HandlerFunc.ServeHTTP(0xdf8f40?, {0x157ad20?, 0x40087bafa0?}, 0x3?)
	net/http/server.go:2122 +0x38
github.com/ethersphere/bee/pkg/jsonhttp.HandleMethods(0x4000d562d0, {0x119317b, 0x2b}, {0x1179ef5, 0x1f}, {0x157ad20?, 0x40087bafa0}, 0x4004da3e00)
	github.com/ethersphere/bee/pkg/jsonhttp/handlers.go:25 +0xf4
github.com/ethersphere/bee/pkg/jsonhttp.MethodHandler.ServeHTTP(0x4004da3d00?, {0x157ad20?, 0x40087bafa0?}, 0xbc6570?)
	github.com/ethersphere/bee/pkg/jsonhttp/handlers.go:17 +0x50
github.com/gorilla/mux.(*Router).ServeHTTP(0x40001b4780, {0x157ad20, 0x40087bafa0}, 0x4004da3c00)
	github.com/gorilla/mux@v1.8.0/mux.go:210 +0x19c
resenje.org/web.NewSetHeadersHandler.func1({0x157ad20, 0x40087bafa0}, 0x10113ee?)
	resenje.org/web@v0.4.3/set_headers.go:28 +0x170
net/http.HandlerFunc.ServeHTTP(0x400899cc30?, {0x157ad20?, 0x40087bafa0?}, 0xd85660?)
	net/http/server.go:2122 +0x38
github.com/ethersphere/bee/pkg/api.(*Service).corsHandler.func1({0x157ad20, 0x40087bafa0}, 0x4004da3c00)
	github.com/ethersphere/bee/pkg/api/api.go:633 +0x3f0
net/http.HandlerFunc.ServeHTTP(0x0?, {0x157ad20?, 0x40087bafa0?}, 0x1?)
	net/http/server.go:2122 +0x38
github.com/gorilla/handlers.CompressHandlerLevel.func1({0x157ad20, 0x40087bafa0}, 0x4004da3c00)
	github.com/gorilla/handlers@v1.4.2/compress.go:148 +0x898
net/http.HandlerFunc.ServeHTTP(0x40080eba08?, {0x157ad20?, 0x40087bafa0?}, 0x3d02a8?)
	net/http/server.go:2122 +0x38
github.com/ethersphere/bee/pkg/log/httpaccess.NewHTTPAccessLogHandler.func1.1({0x157d030?, 0x4004a58b60?}, 0x4004da3c00)
	github.com/ethersphere/bee/pkg/log/httpaccess/http_access.go:41 +0xf4
net/http.HandlerFunc.ServeHTTP(0x10?, {0x157d030?, 0x4004a58b60?}, 0xa0d0?)
	net/http/server.go:2122 +0x38
net/http.serverHandler.ServeHTTP({0x400899cba0?}, {0x157d030, 0x4004a58b60}, 0x4004da3c00)
	net/http/server.go:2936 +0x2c0
net/http.(*conn).serve(0x4008f9b680, {0x157e170, 0x4000270210})
	net/http/server.go:1995 +0x518
created by net/http.(*Server).Serve
	net/http/server.go:3089 +0x4e8
```
### Steps to reproduce
Fire up an ultra-light node and do a /debugstore invocation on the debug API port.

### Possible solution
Check for a non-existant (nil) reserve in ReserveLastBinIDs and return an empty array.
```
func (db *DB) ReserveLastBinIDs() ([]uint64, error) {
	if db.reserve == nil {
		return make([]uint64, 0), nil
	}
	return db.reserve.LastBinIDs(db.repo.IndexStore())
}
```

### PR DESCRIPTION
**Pull request by ldeffenb**
### Checklist

- [x] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md).
- [N/A] My change requires a documentation update, and I have done it.
- [N/A] I have added tests to cover my changes.
- [x] I have filled out the description and linked the related issues.

### Description
Avoid panic if querying ReserveLastBinIDs on ultra-light node with no reserve.

Closes #4270

### Open API Spec Version Changes (if applicable)
N/A

#### Motivation and Context (Optional)
Issue #4270 

### Related Issue (Optional)
#4270

### CODE REVIEW

File: pkg/storer/reserve.go [hunk 1]
```diff
@@ -403,6 +403,9 @@ func (db *DB) unreserve(ctx context.Context) (err error) {
 
 // ReserveLastBinIDs returns all of the highest binIDs from all the bins in the reserve.
 func (db *DB) ReserveLastBinIDs() ([]uint64, error) {
+	if db.reserve == nil {
+		return make([]uint64, 0), nil
```
Comment (mrekucci) [inline pkg/storer/reserve.go:407]: Instead of allocating a new slice a `nil` should be returned.

Comment (ldeffenb) [reply pkg/storer/reserve.go:407]: If I return nil, how will the following line handle that and will the /debugstore response still be correctly formed?   I know the nice empty slice works fine.

https://github.com/ethersphere/bee/blob/0ef39cd0857722e2eb55e9ddaf5a6dee3107d3c0/pkg/storer/debug.go#L150

Comment (ldeffenb) [reply pkg/storer/reserve.go:407]: Not to mention this more-difficult-to-test use of this routine in case some peer requests cursors from an UltraLight node?   I know that's not SUPPOSED to happen, but still a node shouldn't panic if it does occur.

https://github.com/ethersphere/bee/blob/0ef39cd0857722e2eb55e9ddaf5a6dee3107d3c0/pkg/pullsync/pullsync.go#L549

Comment (ldeffenb) [reply pkg/storer/reserve.go]: Changed to nil and verified that at least the /debugstore still works.
```
  "Reserve": {
    "Size": 0,
    "Capacity": 0,
    "LastBinIDs": null
  },
```

**Review by mrekucci — APPROVED** [review]
