### PR TITLE
fix(node): close localstore if migration errors out

### LINKED ISSUE #4820: Migration failure triggers .DIRTY on restart
### Context
Initial run of 2.2.0 upgrading from 2.1.x

### Summary
When I first started this node on 2.2.0, it failed to start due to `It's recommended that the repair-reserve cmd is run first`.   Apparently there's a count discrepancy in the localstore `index counts do not match, 3561491 vs 3561492`.   But that's not actually the problem I'm reporting.

After the error, the node did not shut down cleanly, `kademlia manage loop did not shut down properly: timeout` and therefore, on the restart...

`localstore sharky .DIRTY file exists: starting recovery due to previous dirty exit`

### Expected behavior
I would expect a node that fails a data-dir migration to be able to shut down cleanly, but apparently kademlia expects the database to be function so that it can `kademlia persisting peer metrics` likely resulting in a shutdown deadlock condition.

Now I have to wait for a 1.9TB sharky to recover before finding out if the migration will be attempted a second time before I actually do the `db validate` on this OSM uploading/pinning node. (Note: recovery finished and validate is running.)

### Actual behavior

```
"time"="2024-09-13 12:27:49.429789" "level"="info" "logger"="node" "msg"="using default factory address" "chain_id"=100 "factory_address"="0xC2d5A532cf69AA9A1378737D8ccDEF884B6E7420"
"time"="2024-09-13 12:27:49.441558" "level"="info" "logger"="node/chequebook" "msg"="using existing chequebook" "chequebook_address"="0xB2C617F77d20A32379B5a89761d6E6Fd5a2e2103"
"time"="2024-09-13 12:27:49.639039" "level"="info" "logger"="node" "msg"="using datadir" "path"="/mnt/nvme1/ldeffenb/mainnet/bee-xdai"
"time"="2024-09-13 12:27:51.667482" "level"="info" "logger"="migration-step-06" "msg"="start adding stampHash to BatchRadiusItems, ChunkBinItems and StampIndexItems"
"time"="2024-09-13 12:27:52.348407" "level"="info" "logger"="node/api" "msg"="api access" "ip"="192.168.10.18" "method"="GET" "host"="192.168.10.38:11633" "uri"="/metrics" "proto"="HTTP/1.1" "status"=200 "size"=2672 "duration"="1.065857ms" "user-agent"="Prometheus/2.34.0"
"time"="2024-09-13 12:27:53.378625" "level"="error" "logger"="node" "msg"="got error, shutting down..." "error"="localstore: add stamp hash migration: pre-migration check: index counts do not match, 3561491 vs 3561492. It's recommended that the repair-reserve cmd is run first"
"time"="2024-09-13 12:27:53.381950" "level"="info" "logger"="node/kademlia" "msg"="kademlia shutting down"
"time"="2024-09-13 12:27:58.382635" "level"="info" "logger"="node/kademlia" "msg"="kademlia persisting peer metrics"
"time"="2024-09-13 12:27:58.522849" "level"="error" "logger"="node" "msg"="got error while shutting down" "error"="1 error occurred:\n\t* topology driver: kademlia manage loop did not shut down properly: timeout\n\n"
"time"="2024-09-13 12:27:58.522870" "level"="error" "logger"="node" "msg"="failed to build bee node" "error"="localstore: add stamp hash migration: pre-migration check: index counts do not match, 3561491 vs 3561492. It's recommended that the repair-reserve cmd is run first"
```
And after the restart:
```
"time"="2024-09-13 12:28:49.566575" "level"="info" "logger"="node/storer" "msg"="localstore sharky .DIRTY file exists: starting recovery due to previous dirty exit"
```
Running the `db validate` now, but with that many pinned chunks (494,411,180), it's going to take a LONG time.  Total estimated validate time is 4-5 hours

### Steps to reproduce
Get a 2.1.x node into an inconsistent state and then attempt to migrate to 2.2.0.  I do have a 1.2TB .zip backup of the 2.1.0 data-dir tree, but that's not very practical to deliver to someone for testing.

### Possible solution
Make sure kademlia can shut down cleanly if a migration fails.   Or don't even start kademlia until the migrations have all completed.

### PR DESCRIPTION
**Pull request by istae**
### Checklist

- [x] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md).
- [ ] My change requires a documentation update, and I have done it.
- [ ] I have added tests to cover my changes.
- [x] I have filled out the description and linked the related issues.

### Description
closes #4820

### CODE REVIEW

**Review by martinconic — APPROVED** [review]

**Review by martinconic — APPROVED** [review]

File: pkg/storer/storer.go [hunk 1]
```diff
@@ -482,6 +482,12 @@ func New(ctx context.Context, dirPath string, opts *Options) (*DB, error) {
 		}
 	}
 
+	defer func() {
+		if err != nil {
+			err = errors.Join(err, dbCloser.Close())
```
Comment (martinconic) [inline pkg/storer/storer.go:487]: simpler, smarter

**Review by martinconic — APPROVED** [review]
