### PR TITLE
fix: chunk act upload

### LINKED ISSUE #5007: Upload to the /chunks and /soc endpoints with ACT headers fails
### Context

- Bee v2.5.0-rc4

### Summary
When uploading to the /chunks and /soc endpoints with ACT headers then this results in an error: **"write chunk failed"**.

### Expected behavior
Upload is successful and the encrypted reference is returned in the response.

### Actual behavior
Error message in the bee logs:
`"level"="error" "logger"="node/api/post_soc" "msg"="write chunk failed"`

Relevant code part in **api/soc**:
```
func (s *Service) socUploadHandler(w http.ResponseWriter, r *http.Request) 
...
reference, err = s.actEncryptionHandler(r.Context(), w, putter, reference, headers.HistoryAddress)
...
err = putter.Put(r.Context(), sch)
```

in **api/chunks**:
```
func (s *Service) chunkUploadHandler(w http.ResponseWriter, r *http.Request)
...
reference, err = s.actEncryptionHandler(r.Context(), w, putter, reference, headers.HistoryAddress)
...
err = putter.Put(r.Context(), chunk)
```

### Steps to reproduce
Try to upload to the /soc or /chunks endpoints with the **"Swarm-Act"** header

### Possible solution
The actEncryptionHandler() function is called to encrypt the address of the created chunk, which calls putter.Done() in order to save the history and kvs storage references. However, after putter.Put() is called with the newly created chunk, which then results in the described error. The reason for this is that putter.Done() closes the putter after which putter.Put() cannot be called. 

Calling Put() before the actEncryptionHandler() resolves this issue.

### PR DESCRIPTION
**Pull request by bosi95**
### Checklist

- [ ] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md).
- [ ] My change requires a documentation update, and I have done it.
- [ ] I have added tests to cover my changes.
- [ ] I have filled out the description and linked the related issues.

### Description

- When uploading to the /chunks and /soc endpoints with ACT headers then this results in an error: "write chunk failed". Changes the order of putter.Put and actEncryptionHandler() calls in the /soc and /chunks endpoints during upload.

- Adds the **SwarmActTimestampHeader, SwarmActPublisherHeader, SwarmActHistoryAddressHeader** header to the corsHandler()

### Related Issue (Optional)
fixes #5007

### CODE REVIEW

File: pkg/api/chunk.go [hunk 1]
```diff
@@ -169,6 +169,21 @@ func (s *Service) chunkUploadHandler(w http.ResponseWriter, r *http.Request) {
 		}
 	}
 
+	err = putter.Put(r.Context(), chunk)
+	if err != nil {
+		logger.Debug("chunk upload: write chunk failed", "chunk_address", chunk.Address(), "error", err)
+		logger.Error(nil, "chunk upload: write chunk failed")
+		switch {
+		case errors.Is(err, postage.ErrBucketFull):
+			jsonhttp.PaymentRequired(ow, "batch is overissued")
```
Comment (gacevicljubisa) [inline pkg/api/chunk.go:178]: maybe more clear error msg is appropirate: `the postage batch is overissued and cannot accept more chunks`?

File: pkg/api/api.go [hunk 2]
```diff
@@ -529,7 +529,7 @@ func (s *Service) corsHandler(h http.Handler) http.Handler {
...
-		SwarmTagHeader, SwarmPinHeader, SwarmEncryptHeader, SwarmIndexDocumentHeader, SwarmErrorDocumentHeader, SwarmCollectionHeader, SwarmPostageBatchIdHeader, SwarmPostageStampHeader, SwarmDeferredUploadHeader, SwarmRedundancyLevelHeader, SwarmRedundancyStrategyHeader, SwarmRedundancyFallbackModeHeader, SwarmChunkRetrievalTimeoutHeader, SwarmLookAheadBufferSizeHeader, SwarmFeedIndexHeader, SwarmFeedIndexNextHeader, SwarmSocSignatureHeader, SwarmOnlyRootChunk, GasPriceHeader, GasLimitHeader, ImmutableHeader,
+		SwarmTagHeader, SwarmPinHeader, SwarmEncryptHeader, SwarmIndexDocumentHeader, SwarmErrorDocumentHeader, SwarmCollectionHeader, SwarmPostageBatchIdHeader, SwarmPostageStampHeader, SwarmDeferredUploadHeader, SwarmRedundancyLevelHeader, SwarmRedundancyStrategyHeader, SwarmRedundancyFallbackModeHeader, SwarmChunkRetrievalTimeoutHeader, SwarmLookAheadBufferSizeHeader, SwarmFeedIndexHeader, SwarmFeedIndexNextHeader, SwarmSocSignatureHeader, SwarmOnlyRootChunk, GasPriceHeader, GasLimitHeader, ImmutableHeader, SwarmActHeader, SwarmActTimestampHeader, SwarmActPublisherHeader, SwarmActHistoryAddressHeader,
```
Comment (gacevicljubisa) [inline pkg/api/api.go:532]: Consider splitting it into multiple lines for better readability

File: pkg/api/chunk.go (hunk 1 above)
Comment (acha-bill) [reply pkg/api/chunk.go:178]: I think "batch is overissued" is enough - concise.

File: pkg/api/api.go (hunk 2 above)
Comment (bosi95) [reply pkg/api/api.go]: done: split into multiple lines

**Review by istae — APPROVED** [review]

**Review by gacevicljubisa — APPROVED** [review]
