### PR TITLE
fix(api): direct upload

### LINKED ISSUE #3227: Direct upload gets stuck in dev mode
### Context
Bee 1.7, macOS

### Summary
I was working on an app that uses direct upload (== deferred: false) for uploading chunks. The app is working with a Bee node running on mainnet, however as soon as I try it in dev mode it gets stuck at the first time it tries to upload a chunk. If the same chunk was already uploaded in deferred mode the upload will succeed though.

### Expected behavior
Either the direct upload should work or it should return an error indicating that the direct upload is not supported in dev mode.

### Steps to reproduce
1. Start Bee in dev mode (e.g. `./bee dev`)
2. Buy a postage stamp (`swarm-cli stamp buy --depth 20 --amount 1000000`)
3. Store the postage batch id in an environment variable called `STAMP` (`export STAMP="your-postage-batch-id"`)
4. Generate empty chunk (`dd if=/dev/zero of=./empty count=8 bs=1`)
5. Upload the empty file with direct mode:
```
curl \
    -X POST \
    -H "Swarm-Deferred-Upload: false" \
    -H "Swarm-Postage-Batch-Id: $STAMP" \
    --data-binary @empty http://localhost:1633/chunks
```

The last step will get stuck forever with Bee printing nothing in the logs. If you use the same command but change the deferred upload to `true` then it will be succesful (and after that direct uploads will succeed as well):

```
 % curl \
    -X POST \
    -H "Swarm-Deferred-Upload: true" \ 
    -H "Swarm-Postage-Batch-Id: $STAMP" \
    --data-binary @empty http://localhost:1633/chunks

{"reference":"b34ca8c22b9e982354f9c7f50b470d66db428d880c8a904d5fe4ec9713171526"}

```

### PR DESCRIPTION
**Pull request by umerm-work**
### Checklist

- [x] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md).
- [ ] My change requires a documentation update, and I have done it.
- [ ] I have added tests to cover my changes.
- [ ] I have filled out the description and linked the related issues.

### Description
Closes #3227

- - -
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/3466)

### CODE REVIEW

File: pkg/api/api.go [hunk 1]
```diff
@@ -859,6 +860,9 @@ func (p *pushStamperPutter) Put(ctx context.Context, mode storage.ModePut, chs .
 						}
 						return nil
 					}
+					if errors.Is(err, ErrDevNodeNotSupported) {
```
Comment (aloknerurkar) [inline pkg/api/api.go:863]: This is not required. This error should be returned anyway.

File: pkg/api/chunk.go [hunk 2]
```diff
@@ -70,6 +70,8 @@ func (s *Service) chunkUploadHandler(w http.ResponseWriter, r *http.Request) {
 			jsonhttp.NotFound(w, "batch with id not found")
 		case errors.Is(err, errInvalidPostageBatch):
 			jsonhttp.BadRequest(w, "invalid batch id")
+		case errors.Is(err, ErrDevNodeNotSupported):
```
Comment (aloknerurkar) [inline pkg/api/chunk.go:73]: Why are we handling this error here? We only get the error once the putter is used. We should not get this error here.

File: pkg/node/devnode.go [hunk 3]
```diff
@@ -405,12 +405,21 @@ func NewDevBee(logger log.Logger, o *DevOptions) (b *DevBee, err error) {
...
 
-	apiService.Configure(signer, authenticator, tracer, api.Options{
+	chunkC := apiService.Configure(signer, authenticator, tracer, api.Options{
 		CORSAllowedOrigins: o.CORSAllowedOrigins,
 		WsPingPeriod:       60 * time.Second,
 		Restricted:         o.Restricted,
 	}, debugOpts, 1, erc20)
-
+	go func() {
+		for {
```
Comment (aloknerurkar) [inline pkg/node/devnode.go:414]: This goroutine needs to be stopped on shutdown. Right now its leaking. We need to have select here to select chunk or shutdown signal.

**Review by aloknerurkar — CHANGES_REQUESTED** [review]

File: pkg/api/chunk.go (hunk 2 above)
Comment (umerm-work) [reply pkg/api/chunk.go:73]: Forgot to remove this.

**Comment by aloknerurkar** [comment]
The commit message is not correct. The part in the `()` needs to be the package we are changing. `chunk` is not the correct name. It would be better to use nothing if you are not sure. But ideally this should be `api` package change.

File: pkg/api/api.go (hunk 1 above)
Comment (umerm-work) [reply pkg/api/api.go:863]: It's not returning this error. That is why I have to write it explicitly.

File: pkg/node/devnode.go (hunk 3 above)
Comment (umerm-work) [reply pkg/node/devnode.go:414]: @aloknerurkar, where can I get the `shutdown` signal from? Is there already something available in this file?

Comment (aloknerurkar) [reply pkg/node/devnode.go:414]: What you can do is use for loop over the channel. Then you can close this channel in the Shutdown function. Please try to go through the code and understand how all this works.

File: pkg/node/devnode.go [hunk 4]
```diff
@@ -405,12 +405,23 @@ func NewDevBee(logger log.Logger, o *DevOptions) (b *DevBee, err error) {
...
+			select {
+			case ch := <-chunkC:
+				if ch.Direct {
+					ch.Err <- api.ErrDevNodeNotSupported
+					return
```
Comment (aloknerurkar) [inline pkg/node/devnode.go:419]: This is completely wrong. We cannot stop the routine the first time we get chunk on the channel. We need to send error for each chunk.

Also, what is the point of the double return? 

This routine needs to be running till shutdown is called. The shutdown should send some signal for this to stop.

Comment (umerm-work) [reply pkg/node/devnode.go:419]: You are right. Corrected this mistake yesterday but still trying to find the shutdown signal.

File: pkg/node/devnode.go [hunk 5]
```diff
@@ -72,6 +72,7 @@ type DevBee struct {
 	errorLogWriter   io.Writer
 	apiServer        *http.Server
 	debugAPIServer   *http.Server
+	quitChunk        chan bool
```
Comment (aloknerurkar) [inline pkg/node/devnode.go:75]: `chan bool` is not required. You can instead use `chan struct{}`. This is more optimal.

File: pkg/node/devnode.go [hunk 6]
```diff
@@ -462,6 +474,7 @@ func NewDevBee(logger log.Logger, o *DevOptions) (b *DevBee, err error) {
 func (b *DevBee) Shutdown() error {
 	var mErr error
 
+	b.quitChunk <- true
```
Comment (aloknerurkar) [inline pkg/node/devnode.go:477]: You can `close(b.quitChunk)` instead of passing value here. It does the same thing.

File: pkg/node/devnode.go [hunk 7]
```diff
@@ -405,12 +406,23 @@ func NewDevBee(logger log.Logger, o *DevOptions) (b *DevBee, err error) {
...
 	apiService := api.New(mockKey.PublicKey, mockKey.PublicKey, overlayEthAddress, logger, mockTransaction, batchStore, api.DevMode, true, true, chainBackend, o.CORSAllowedOrigins)
 
-	apiService.Configure(signer, authenticator, tracer, api.Options{
+	chunkC := apiService.Configure(signer, authenticator, tracer, api.Options{
 		CORSAllowedOrigins: o.CORSAllowedOrigins,
 		WsPingPeriod:       60 * time.Second,
 		Restricted:         o.Restricted,
 	}, debugOpts, 1, erc20)
-
+	go func() {
```
Comment (aloknerurkar) [inline pkg/node/devnode.go:414]: Add some comment here on why this new goroutine is needed.

File: pkg/node/devnode.go (hunk 5 above)
Comment (aloknerurkar) [inline pkg/node/devnode.go:75]: This should be called `quitErrPusher` or something. As you are replicating a pusher which returns error.

**Review by aloknerurkar — CHANGES_REQUESTED** [review]

File: pkg/node/devnode.go (hunk 6 above)
Comment (umerm-work) [reply pkg/node/devnode.go:477]: But we have to send a signal to goroutine to close it. If we close it without passing a signal then the code will panic.

Comment (aloknerurkar) [reply pkg/node/devnode.go]: So you need to understand how the channels work. Even if you close the channel, you can read from it and it will tell you that it is closed.

```
c := make(chan struct{})
close(c)
// this next operation is okay and it will immediately return as the channel is closed. The second parameter
// tells you that it is closed. But we dont care about it as this channel is only used to signal. So no need to write
// anything in it.
<-c
```

This type of pattern is used all over the code. You can follow any closer method implemented by the packages and see.

Comment (umerm-work) [reply pkg/node/devnode.go]: Thanks for explanation.

File: pkg/node/devnode.go [hunk 8]
```diff
@@ -405,12 +407,24 @@ func NewDevBee(logger log.Logger, o *DevOptions) (b *DevBee, err error) {
...
 	apiService := api.New(mockKey.PublicKey, mockKey.PublicKey, overlayEthAddress, logger, mockTransaction, batchStore, api.DevMode, true, true, chainBackend, o.CORSAllowedOrigins)
 
-	apiService.Configure(signer, authenticator, tracer, api.Options{
+	chunkC := apiService.Configure(signer, authenticator, tracer, api.Options{
 		CORSAllowedOrigins: o.CORSAllowedOrigins,
 		WsPingPeriod:       60 * time.Second,
 		Restricted:         o.Restricted,
 	}, debugOpts, 1, erc20)
-
+	// this sends signal to the pusher that direct upload is not supported in dev mode
```
Comment (aloknerurkar) [inline pkg/node/devnode.go:415]: This doesnt send signal to pusher. It sends signal to the putter in the API.

**Review by mrekucci — CHANGES_REQUESTED** [review]
I'd suggest testing to see if the same problem also occurs on the `/bytes`, `/bzz`, and `/feed` endpoints. If this is the case, I'd suggest addressing it in the `newStamperPutter` method, where `s.beeMode` can be queried and `deferred` information is available.

**Comment by umerm-work** [comment]
> 
So yes this problem occurs in `/bytes` and `/bzz` endpoints but not sure about `/feed` since it requires an Ethereum address as a param and in dev mode, we don't have any address.

**Comment by agazso** [comment]
> > 
> 
> So yes this problem occurs in `/bytes` and `/bzz` endpoints but not sure about `/feed` since it requires an Ethereum address as a param and in dev mode, we don't have any ethereum address.

The `/feed` requires a feed address, that indeed is the same format as the ethereum address (because it uses the same elliptic curve cryptography to generate addresses), but it is independent of the node's own ethereum address. In fact any valid ethereum address can be used as a feed address.

**Comment by umerm-work** [comment]
> > > 
> > 
> > 
> > So yes this problem occurs in `/bytes` and `/bzz` endpoints but not sure about `/feed` since it requires an Ethereum address as a param and in dev mode, we don't have any ethereum address.
> 
> The `/feed` requires a feed address, that indeed is the same format as the ethereum address (because it uses the same elliptic curve cryptography to generate addresses), but it is independent of the node's own ethereum address. In fact any valid ethereum address can be used as a feed address.

Thanks So `/bytes` , `/bzz` and `/feed` are giving `bad request`  in response and they don't hang the request like in `/chunk` endpoint. Soo just going to add message `dev node not supported`

File: pkg/api/api.go [hunk 9]
```diff
@@ -113,6 +113,7 @@ var (
 	errFileStore            = errors.New("could not store file")
 	errInvalidPostageBatch  = errors.New("invalid postage batch id")
 	errBatchUnusable        = errors.New("batch not usable")
+	ErrDevNodeNotSupported  = errors.New("dev node not supported")
```
Comment (mrekucci) [inline pkg/api/api.go:116]: I'd change the error to `errUnsupportedDevNodeOperation  = errors.New("operation not supported in dev mode")`. Also, the error doesn't have to be exported, re-export can be done in the `export_test.go` file if needed in tests.

**Review by mrekucci — APPROVED** [review]

File: pkg/api/chunk.go [hunk 10]
```diff
@@ -161,8 +163,14 @@ func (s *Service) chunkUploadHandler(w http.ResponseWriter, r *http.Request) {
 
 	if err = wait(); err != nil {
 		s.logger.Debug("chunk upload: sync chunk failed", "error", err)
-		s.logger.Error(nil, "chunk upload: sync chunk failed")
-		jsonhttp.InternalServerError(w, "sync failed")
+		switch {
+		case errors.Is(err, errUnsupportedDevNodeOperation):
+			s.logger.Error(nil, "chunk upload: direct upload not supported in dev mode")
```
Comment (aloknerurkar) [inline pkg/api/chunk.go:168]: Would be better to send the err here and in the default case to the log.Error. So we can see it in logs also.

**Review by aloknerurkar — APPROVED** [review]
