### PR TITLE
fix: stream related metrics

### LINKED ISSUE #3439: Increase visibility into stream creation and closing
⚠️ Support requests in an issue-format will be closed immediately. For support, go to Swarm's [Discord](https://discord.gg/XGNBEKktkD).

### Context
It seems that libp2p does not always release the resource allocated to a stream after it has been closed.
We need some metrics around stream creation and closing to be able to zoom in on the underlying issue.

Related #2983 #3075 

### Summary
We need to increase visibility into how a chunk is being forwarded/store/rejected in order to zoom in on the issue.
This would allow to discern if the root cause is a bug in the application logic or in the libp2p stream handling logic.

### PR DESCRIPTION
**Pull request by notanatol**
### Checklist

- [X] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md).
- [X] I have filled out the description and linked the related issues.

### Description
We need metrics to see how many streams we are closing/resetting and how many closed streams libp2p library reports.

#### Motivation and Context (Optional)
It's likely the libp2p library does not releases the resources after a stream is closed.

### Related Issue (Optional)
Closes #3439

- - -
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/3474)

### CODE REVIEW

**Review by istae — APPROVED** [review]

File: pkg/p2p/libp2p/connections_test.go [hunk 1]
```diff
@@ -543,7 +543,9 @@ func TestConnectRepeatHandshake(t *testing.T) {
 		t.Fatal(err)
 	}
 
-	if _, err := s2.HandshakeService().Handshake(ctx, libp2p.NewStream(stream), info.Addrs[0], info.ID); err != nil {
+	s := s2.WrapStream(stream)
```
Comment (mrekucci) [inline pkg/p2p/libp2p/connections_test.go:546]: Since `s` is only used in the `Handshake` method, I would suggest nesting it there.

File: pkg/p2p/libp2p/libp2p.go [hunk 2]
```diff
@@ -1080,6 +1084,25 @@ func (c *connectionNotifier) Connected(_ network.Network, _ network.Conn) {
 	c.metrics.HandledConnectionCount.Inc()
 }
 
+func newStreamMetricNotify(m metrics) *streamNotifier {
```
Comment (mrekucci) [inline pkg/p2p/libp2p/libp2p.go:1087]: I'd name it `newStreamNotifier`.

**Review by mrekucci — APPROVED** [review]
