### PR TITLE
fix: upload store fixes

### LINKED ISSUE #4541: uploadstore fixes
* stampindex check can be removed in the `uploadPutter.Put` as the chunks passed to the putter are refreshly uploaded and stamped chunks.
* `uploadPutter.Close` should delete all associated uploadItems and chunk data, see `remove()` (confirm this is currently leaking).
* `Report` should not fetch `uploadItem` for the tagID but can use the tagID directly from the chunk (it must assured that the callers of `Report` has a chunk with a properly set tagID)
* see https://hackmd.io/D3lK13p6S8egANbvkrIYSw#Deferred-Uploads for more description

### PR DESCRIPTION
**Pull request by acha-bill**
### Checklist

- [x] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md).
- [ ] My change requires a documentation update, and I have done it.
- [x] I have added tests to cover my changes.
- [ ] I have filled out the description and linked the related issues.

### Description

1. Remove stamp index check from `uploadPutter.Put`
2. Delete all associated uploadItems after close

### Related Issue (Optional)
Closes #4541

### CODE REVIEW

**Comment by istae** [comment]
we should also add a new migration step that removes all leftover items from previous sessions.
in the next release, we can add a line in the release notes that the new release will cleanup all upload items so that before deploying the new release, all uploads must first finish.

File: pkg/storer/migration/step_05.go [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+	"github.com/ethersphere/bee/pkg/storage"
+	"github.com/ethersphere/bee/pkg/storer/internal/upload"
+)
+
+// step_05 is a migration step that removes all upload items from the store.
+func step_05(st storage.BatchedStore) error {
+	logger := log.NewLogger("migration-step-05", log.WithSink(os.Stdout))
+	logger.Info("start removing upload items")
+
+	var itemsToDelete []storage.Item
```
Comment (istae) [inline pkg/storer/migration/step_05.go:21]: there is a chance you might blow up the memory.
i would use a channel here so that one worker feeds the items, the other picks them up and deletes from storage

**Review by istae — CHANGES_REQUESTED** [review]

File: pkg/storer/internal/upload/uploadstore.go [hunk 2]
```diff
@@ -848,15 +827,31 @@ func DeleteTag(st storage.Store, tagID uint64) error {
...
 	return st.Iterate(
 		storage.Query{
 			Factory: func() storage.Item { return new(uploadItem) },
 		},
 		func(r storage.Result) (bool, error) {
-			address := swarm.NewAddress([]byte(r.ID[:32]))
-			synced := r.Entry.(*uploadItem).Synced != 0
-			return iterateFn(address, synced)
+			ui := r.Entry.(*uploadItem)
+			ui.IdFunc = func() string {
```
Comment (istae) [inline pkg/storer/internal/upload/uploadstore.go:837]: what is the purpose of this?

**Review by istae — CHANGES_REQUESTED** [review]

File: pkg/storer/internal/upload/uploadstore.go (hunk 2 above)
Comment (acha-bill) [reply pkg/storer/internal/upload/uploadstore.go:837]: when uploadItems are marshalled, the address and batchID (which make up the ID) are not stored. 
It was assumed that the user would always know these properties when trying to get the item from the store. 
```
ui := &uploadItem {
   Address: addr,
   BatchID: id,
}
store.Get(ui)
```
So there was no need to save the address and batch to storage.

But this is a problem when iterating the store. 
Since the address and batchID were not stored, the resulting upload items don't have a unique ID.
```
iterate(func (r Result) {
  ui := r.Entry.(*uploadItem)
  println(ui.ID() == "/") // true (since address and batchID are empty, ID() == "/" for all items
  
  // Luckily, the ID is stored in the `Result`. I introduced IdFunc here as a workaround
  ui.IdFunc = func() { return r.ID }
}
```

Comment (istae) [reply pkg/storer/internal/upload/uploadstore.go:837]: got it, thanks.

**Review by notanatol — APPROVED** [review]

**Review by istae — APPROVED** [review]
