### PR TITLE
fix: act expose headers

### LINKED ISSUE #5023: ACT headers are not added to the expose headers
### Context
- Bee v2.5.0-rc6, master

### Summary
When uploading to any of the api endpoints the ACT relevant headers, i.e.: history address, are not added to the expose headers.
It was reported in issue #5007 

### Expected behavior
The ACT headers are in the expose headers, if they are present.

### Actual behavior
Right now the **SwarmActHistoryAddressHeader** is set but not added to the expose headers.

### Steps to reproduce
Upload to any of the endpoints with the **Swarm-Act** header. Check the expose headers.

### Possible solution
Add the **SwarmActHistoryAddressHeader** to the **AccessControlExposeHeaders**, only if the **Swarm-Act** is set.

### PR DESCRIPTION
**Pull request by bosi95**
### Checklist
- [ ] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md).
- [ ] My change requires a documentation update, and I have done it.
- [ ] I have added tests to cover my changes.
- [ ] I have filled out the description and linked the related issues.

### Description
When uploading to any of the api endpoints the ACT relevant headers, i.e.: history address, are not added to the expose headers.
Adds the **SwarmActHistoryAddressHeader** to the **AccessControlExposeHeaders**, only if the **Swarm-Act** is set.

### Open API Spec Version Changes (if applicable)
-
#### Motivation and Context (Optional)
-
### Related Issue (Optional)
fixes #5023 

### Screenshots (if appropriate):
image

### CODE REVIEW

**Review by acha-bill — APPROVED** [review]

File: pkg/api/accesscontrol.go [hunk 1]
```diff
@@ -154,32 +154,30 @@ func (s *Service) actDecryptionHandler() func(h http.Handler) http.Handler {
 // uploads the encrypted reference, history and kvs to the store.
 func (s *Service) actEncryptionHandler(
 	ctx context.Context,
-	w http.ResponseWriter,
 	putter storer.PutterSession,
 	reference swarm.Address,
 	historyRootHash swarm.Address,
-) (swarm.Address, error) {
+) (swarm.Address, swarm.Address, error) {
```
Comment (gacevicljubisa) [inline pkg/api/accesscontrol.go:160]: Consider using named return values for clarity.
`(encryptedRef, historyRef swarm.Address, err error)`

**Review by gacevicljubisa — APPROVED** [review]

**Review by martinconic — APPROVED** [review]
