### PR TITLE
fix(localstore): out of memory issue during unreserve

### LINKED ISSUE #3123: bee oom loop even with 6gb ram
⚠️ Support requests in an issue-format will be closed immediately. For support, go to Swarm's [Discord](https://discord.gg/XGNBEKktkD).

### Context
1.7.0

### Summary
Bee uses 6gb+ memory

### Expected behavior
Should work fine with 3-4gb ?!

### Actual behavior
````
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Tue, 26 Jul 2022 18:01:30 +0200
      Finished:     Tue, 26 Jul 2022 18:17:54 +0200
````
bee-oom

### Steps to reproduce
N/A

### Possible solution
nuke db

logs:
[bee.log](https://github.com/ethersphere/bee/files/9191639/bee.log)
[bee-previous.log](https://github.com/ethersphere/bee/files/9191640/bee-previous.log)
[dump1.log](https://github.com/ethersphere/bee/files/9191643/dump1.log)
[dump2.log](https://github.com/ethersphere/bee/files/9191644/dump2.log)

[heap.log](https://github.com/ethersphere/bee/files/9196266/heap.log)
[allocs.log](https://github.com/ethersphere/bee/files/9196267/allocs.log)

localstore log:
[LOG.log](https://github.com/ethersphere/bee/files/9191659/LOG.log)
[LOG.old.log](https://github.com/ethersphere/bee/files/9191660/LOG.old.log)

### PR DESCRIPTION
**Pull request by aloknerurkar**
### Checklist

- [x] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md)
- [ ] My change requires a documentation update and I have done it
- [x] I have added tests to cover my changes.
- [x] I have filled out the description and linked the related issues

### Description
Fixes #3123

- - -
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/3247)

### CODE REVIEW

File: pkg/localstore/reserve.go [hunk 1]
```diff
@@ -105,22 +73,91 @@ func (db *DB) UnreserveBatch(id []byte, radius uint8) (evicted uint64, err error
...
-		if err := db.incReserveSizeInBatch(batch, -int64(reserveSizeChange)); err != nil {
+	// trigger garbage collection if we reached the capacity
+	if gcSize >= db.cacheCapacity {
+		db.triggerGarbageCollection()
+	}
+
+	return reserveSizeChange, nil
+}
+
+var unpinBatchSize = 10000
```
Comment (mrekucci) [inline pkg/localstore/reserve.go:84]: Can be a constant.

File: pkg/localstore/reserve.go [hunk 2]
```diff
@@ -105,22 +73,91 @@ func (db *DB) UnreserveBatch(id []byte, radius uint8) (evicted uint64, err error
...
+		}
+
+		gcSizeChange += c
+		return false, nil
+	}
+
+	var startItem *shed.Item
+	for {
+		currentBatchSize := 0
+		more := false
```
Comment (mrekucci) [inline pkg/localstore/reserve.go:120]: I think it would be more readable if you put the `more` variable as the loop param: `for more := fale; !more; {` and get rid of the break statement at the end of the loop.

**Review by mrekucci — APPROVED** [review]

**Review by notanatol — APPROVED** [review]

File: pkg/localstore/reserve.go (hunk 1 above)
Comment (aloknerurkar) [reply pkg/localstore/reserve.go:84]: So in the test, I am changing this value. It was too large for the test.

File: pkg/localstore/reserve.go (hunk 2 above)
Comment (aloknerurkar) [reply pkg/localstore/reserve.go:120]: So if more is true we need to continue. And the initial value needs to be false. This is why I am not sure if it can be done using this type of for loop.

File: pkg/localstore/reserve.go (hunk 1 above)
Comment (mrekucci) [reply pkg/localstore/reserve.go:84]: Sorry, didn't catch that.

File: pkg/localstore/reserve.go (hunk 2 above)
Comment (mrekucci) [reply pkg/localstore/reserve.go:120]: Yes, you're right, I miss that.

**Review by mrekucci — APPROVED** [review]
