### PR TITLE
fix: add transaction hash

### LINKED ISSUE #3359: Return transaction hash for endpoints that creates transactions
To my knowledge, when a user calls some Bee's endpoint which creates a transaction on a blockchain, it then awaits several confirmations before incorporating the requested change it into its internal state. For the creation of postage stamps, this is solved using the `usable` flag which indicates that the stamp is not ready to be used yet. This solves it only for this endpoint, but actually, there are several endpoints that are not handled and this creates a problem for handling these actions in UIs.

Imagine, that as a user of Swarm Desktop you decide to, for example, dilute a postage batch. You click fill out the form with information and submit it. The spinning wheel will appear (the API request to Bee endpoint is sent), then it disappears without any error and it seems like it was a success (the API request was finished, we got Response from Bee), but then the user refreshes the page (or Swarm Desktop does it for him) but nothing has changed! 😱 Well that is because of this "void period" when Bee internally awaits the confirmations... 

For the creation of postage batches, we can regularly poll the batch detail to see if it is ready, but for other actions, this is not true. To my knowledge, there is no way how to handle this case with the API at the moment. There is the `GET /transaction` endpoint on Debug API, but if there are more transactions happening at the same time, then we can not map these to the proper API call.

There are two solutions I can see:
 1. Return response for the API call, only after Bee gets its confirmations. 
 2. For all transaction creation endpoints, return also the transaction hash.

I am more in favor of the second solution, as having an open request for even several minutes does not sound really like a great idea.

### PR DESCRIPTION
**Pull request by umerm-work**
### Checklist

- [x] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md).
- [x] My change requires a documentation update, and I have done it.
- [x] I have added tests to cover my changes.
- [x] I have filled out the description and linked the related issues.

### Description
Closes #3359 

### Screenshots (if appropriate):

- - -
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/3535)

### CODE REVIEW

**Review by notanatol — APPROVED** [review]

File: pkg/postage/postagecontract/contract.go [hunk 1]
```diff
@@ -263,49 +263,49 @@ func (c *postageContract) getBalance(ctx context.Context) (*big.Int, error) {
...
 	err = c.ExpireBatches(ctx)
 	if err != nil {
-		return nil, err
+		return "", nil, err
 	}
 
 	_, err = c.sendApproveTransaction(ctx, totalAmount)
 	if err != nil {
-		return nil, err
+		return "", nil, err
```
Comment (swarmHaseeb) [inline pkg/postage/postagecontract/contract.go:289]: We can also return transaction hash in case of a failed transaction for more information. I also propose to add them to debug logs for easier debugging. 
Also in case of a failed transaction it would be wise to know the Gas Price and other related information (Tip/boost percent etc) for debugging purposes.
If you look at pkg/transaction/transaction.go Line 164 ` err = t.backend.SendTransaction(ctx, signedTx)` it looks like what Abel planned was to return the tx hash in case of error and he probably may have left it in the middle (or had planned to complete it later in another PR) so you can use that to actually get the details of transaction more easily. @istae

**Review by swarmHaseeb — CHANGES_REQUESTED** [review]

File: pkg/postage/postagecontract/contract.go (hunk 1 above)
Comment (umerm-work) [reply pkg/postage/postagecontract/contract.go:289]: So we already sending an error here, which is being handled in the endpoint. I think the error is enough to describe the failure of the transaction.

File: openapi/SwarmCommon.yaml [hunk 2]
```diff
@@ -385,6 +385,8 @@ components:
       properties:
         batchID:
           $ref: "#/components/schemas/BatchID"
+        txHash:
```
Comment (istae) [inline openapi/SwarmCommon.yaml:388]: please update version

File: pkg/api/postage.go [hunk 3]
```diff
@@ -461,7 +463,7 @@ func (s *Service) postageTopUpHandler(w http.ResponseWriter, r *http.Request) {
 	}
 	hexBatchID := hex.EncodeToString(paths.BatchID)
 
-	err := s.postageContract.TopUpBatch(r.Context(), paths.BatchID, paths.Amount)
+	_, err := s.postageContract.TopUpBatch(r.Context(), paths.BatchID, paths.Amount)
```
Comment (istae) [inline pkg/api/postage.go:466]: missing transaction in the json response

File: pkg/api/postage.go [hunk 4]
```diff
@@ -499,7 +501,7 @@ func (s *Service) postageDiluteHandler(w http.ResponseWriter, r *http.Request) {
 	}
 	hexBatchID := hex.EncodeToString(paths.BatchID)
 
-	err := s.postageContract.DiluteBatch(r.Context(), paths.BatchID, paths.Depth)
+	_, err := s.postageContract.DiluteBatch(r.Context(), paths.BatchID, paths.Depth)
```
Comment (istae) [inline pkg/api/postage.go:504]: missing transaction in the json response

File: pkg/postage/postagecontract/contract.go [hunk 5]
```diff
@@ -263,49 +263,49 @@ func (c *postageContract) getBalance(ctx context.Context) (*big.Int, error) {
 	return abi.ConvertType(results[0], new(big.Int)).(*big.Int), nil
 }
 
-func (c *postageContract) CreateBatch(ctx context.Context, initialBalance *big.Int, depth uint8, immutable bool, label string) ([]byte, error) {
+func (c *postageContract) CreateBatch(ctx context.Context, initialBalance *big.Int, depth uint8, immutable bool, label string) (string, []byte, error) {
 
 	if depth <= BucketDepth {
-		return nil, ErrInvalidDepth
+		return "", nil, ErrInvalidDepth
```
Comment (istae) [inline pkg/postage/postagecontract/contract.go:269]: i would use naked returns or named returns values to make the change more "pretty" and get rid of all of the quotes

File: pkg/postage/postagecontract/contract.go [hunk 6]
```diff
@@ -263,49 +263,49 @@ func (c *postageContract) getBalance(ctx context.Context) (*big.Int, error) {
 	return abi.ConvertType(results[0], new(big.Int)).(*big.Int), nil
 }
 
-func (c *postageContract) CreateBatch(ctx context.Context, initialBalance *big.Int, depth uint8, immutable bool, label string) ([]byte, error) {
+func (c *postageContract) CreateBatch(ctx context.Context, initialBalance *big.Int, depth uint8, immutable bool, label string) (string, []byte, error) {
```
Comment (istae) [inline pkg/postage/postagecontract/contract.go:266]: ideally, instead of a string, it should return `common.Hash` type

File: pkg/postage/postagecontract/contract.go (hunk 1 above)
Comment (istae) [reply pkg/postage/postagecontract/contract.go:289]: we log the transaction actually, it's done by the transaction monitor service
./pkg/transaction/monitor.go L103

**Review by istae — CHANGES_REQUESTED** [review]

File: pkg/postage/postagecontract/contract.go (hunk 6 above)
Comment (umerm-work) [reply pkg/postage/postagecontract/contract.go:266]: So I initially set it to `common.Hash`  but thought we only going to use string. Any specific reason for `common.Hash`?

**Review by swarmHaseeb — APPROVED** [review]

File: pkg/postage/postagecontract/contract.go (hunk 6 above)
Comment (istae) [reply pkg/postage/postagecontract/contract.go:266]: it's more specific, easier to read/understand, similar to how we return swarm.Address instead of []byte

File: openapi/SwarmCommon.yaml (hunk 2 above)
Comment (umerm-work) [reply openapi/SwarmCommon.yaml:388]: @istae sorry, which version should it be?

**Review by istae — APPROVED** [review]
