### PR TITLE
fix: redundancy root push

### LINKED ISSUE #4705: Overzealous (and constant) single chunk redundancy
### Context
2.1.0

### Summary
I'm trying to evaluate the impact of including redundancy on the next version upload of the OSM dataset which is very heavy with single chunk mantaray nodes.  But according to my trace logs, specifying ANY redundancy level but zero results in 17 chunks being stamped and pushed into the swarm instead of the original single 1.   This is WAY too expensive for a dataset which has 26,309,262 mantaray node chunks indexing 22,481,003 individual PNG files.   That 26 million would be multiplied by 17!

### Expected behavior
I expected the different redundancy levels to generate different numbers of chunks for this 128 byte /bytes upload, but every non-zero level generates the same 17 chunks, 16 of which are apparently generated by the redundancy code.

### Actual behavior
Using this file which is a binary copy of a mantaray node (you need to unzip it):
[d50c26a504619838ff1fd1cc86ed69b9b6b380f484b3a0444015df500322f4c6.zip](https://github.com/user-attachments/files/15598005/d50c26a504619838ff1fd1cc86ed69b9b6b380f484b3a0444015df500322f4c6.zip)
And this command to do the upload:
```
curl -X POST -H "swarm-deferred-upload: false" -H "swarm-postage-batch-id: {putYourBatchHere}" -H "swarm-redundancy-level: 0" -q --data-binary @d50c26a504619838ff1fd1cc86ed69b9b6b380f484b3a0444015df500322f4c6.bytes http://localhhost1633/bytes
```
as expected, I get the following response:
`{"reference":"d50c26a504619838ff1fd1cc86ed69b9b6b380f484b3a0444015df500322f4c6"}
`
My debug logs (see Steps to reproduce) show me the single chunk.
```
"msg"="putTrace: Put" "chunk"="d50c26a504619838ff1fd1cc86ed69b9b6b380f484b3a0444015df500322f4c6"
"msg"="putTrace: Done" "ref"="d50c26a504619838ff1fd1cc86ed69b9b6b380f484b3a0444015df500322f4c6"
```
But if I set the `swarm-redundancy-level` to any value from 1-4,
```
curl -X POST -H "swarm-deferred-upload: false" -H "swarm-postage-batch-id: {putYourBatchHere}" -H "swarm-redundancy-level: 1" -q --data-binary @d50c26a504619838ff1fd1cc86ed69b9b6b380f484b3a0444015df500322f4c6.bytes http://localhhost1633/bytes
curl -X POST -H "swarm-deferred-upload: false" -H "swarm-postage-batch-id: {putYourBatchHere}" -H "swarm-redundancy-level: 2" -q --data-binary @d50c26a504619838ff1fd1cc86ed69b9b6b380f484b3a0444015df500322f4c6.bytes http://localhhost1633/bytes
curl -X POST -H "swarm-deferred-upload: false" -H "swarm-postage-batch-id: {putYourBatchHere}" -H "swarm-redundancy-level: 3" -q --data-binary @d50c26a504619838ff1fd1cc86ed69b9b6b380f484b3a0444015df500322f4c6.bytes http://localhhost1633/bytes
curl -X POST -H "swarm-deferred-upload: false" -H "swarm-postage-batch-id: {putYourBatchHere}" -H "swarm-redundancy-level: 4" -q --data-binary @d50c26a504619838ff1fd1cc86ed69b9b6b380f484b3a0444015df500322f4c6.bytes http://localhhost1633/bytes
```
I get the following logs.   Note that the order of the chunks being logged varies, but it is always the same additional 16 chunks.
```
"msg"="putTrace: Put" "chunk"="d50c26a504619838ff1fd1cc86ed69b9b6b380f484b3a0444015df500322f4c6"
"msg"="putTrace: Put" "chunk"="d50c26a504619838ff1fd1cc86ed69b9b6b380f484b3a0444015df500322f4c6"
"msg"="putTrace: Put" "chunk"="92c8d84741368ed08b3d9df4a1924c93fd7c5c71c92bfad25ab462f31f285ed2"
"msg"="putTrace: Put" "chunk"="33f4de243b13d27b7e1a9cbf302b21e282a7813ff5cd7a8711fcf7f8a4078bcb"
"msg"="putTrace: Put" "chunk"="fbb12554ff101f5f71e7de7da03a69396843ede907da93b49d65b66736162fcc"
"msg"="putTrace: Put" "chunk"="d2b1cff38b6efcc3f336e2fc898fc40ac8d5b0290f614cd8046eaaa2039e8c9e"
"msg"="putTrace: Put" "chunk"="ab0976831ccb2a92666cc5670a3fc48353ebb3c3e534fd493bee9bfb20ef0c9c"
"msg"="putTrace: Put" "chunk"="6aa9bb4def9e3847d19edfa502a4a2eb4f4ab203a446d3de744ca29b0abd337e"
"msg"="putTrace: Put" "chunk"="1cee43ae46aee79e31246d6bbbb4b19a8f0d8cf8e398c1e63da900b19acf10bf"
"msg"="putTrace: Put" "chunk"="e053b743974bf28d9eeedd501f9ddac62b5ec504a3d653e2b711bafe91412386"
"msg"="putTrace: Put" "chunk"="54926a66b4a10f79ccc1df26bad7b3cc5db15ab9c11879fd536ec1be0dd3542c"
"msg"="putTrace: Put" "chunk"="83e7774ad50864e5eecf6e2981eebd6fcf38b4b50b6548c253d3cdd9d4e8ffbe"
"msg"="putTrace: Put" "chunk"="0104024d50e391823a2bd7ba19720cb6b1f531abacf570e03ac6ff91aefb648c"
"msg"="putTrace: Put" "chunk"="23a1105fb7de6953c835b7015c8494c8d1ea035aaebe2b60b3c8235f5564cca6"
"msg"="putTrace: Put" "chunk"="bdfafec94241c8f699c1bcfa27a34fef3a6b58d44bc6c8d3508d090ad3669051"
"msg"="putTrace: Put" "chunk"="77a6ee451130cb00d6aff52f339f99d95af40903eb8f665ca04114a7eedfa10f"
"msg"="putTrace: Put" "chunk"="48112bdca4e2ade9b0ef54f3f83d3a778ad3173ef68a5da210e512d6fe5db775"
"msg"="putTrace: Put" "chunk"="c849e53e7bf37f8770dfee71fcca69348eb9372ce16eea8ac3cfff5819acf58f"
"msg"="putTrace: Done" "ref"="d50c26a504619838ff1fd1cc86ed69b9b6b380f484b3a0444015df500322f4c6"
```
I also find it strange that the root chunk reference goes through the Put() method twice.   Seems a bit redundant if you ask me.

### Steps to reproduce
Add the putter logs found in my hacked version then execute the previous upload commands.   You'll see the generated chunks that are being pushed into the swarm.
https://github.com/ldeffenb/bee/blob/f73bf0897dd3c401751241c5aab3a1819a5bb9d3/pkg/api/api.go#L792
https://github.com/ldeffenb/bee/blob/f73bf0897dd3c401751241c5aab3a1819a5bb9d3/pkg/api/api.go#L801

### Possible solution
I really don't know, but I suspect this hard-coded constant has something to do with it.   Note that this applies for any non-zero level, although I cannot explain why I get 16 chunks when this constant is 8.
https://github.com/ethersphere/bee/blob/8c61408db7cd63227cfe161967e3b70f90b9fde3/pkg/file/redundancy/redundancy.go#L58-L60

### PR DESCRIPTION
**Pull request by nugaon**
Closes #4705

### Checklist

- [ ] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md).
- [ ] My change requires a documentation update, and I have done it.
- [ ] I have added tests to cover my changes.
- [ ] I have filled out the description and linked the related issues.

### CODE REVIEW

File: pkg/replicas/putter.go [hunk 1]
```diff
@@ -31,9 +31,9 @@ func NewPutter(p storage.Putter) storage.Putter {
 // Put makes the getter satisfy the storage.Getter interface
 func (p *putter) Put(ctx context.Context, ch swarm.Chunk) (err error) {
 	rlevel := redundancy.GetLevelFromContext(ctx)
-	errs := []error{p.putter.Put(ctx, ch)}
+	errs := []error{}
```
Comment (ldeffenb) [inline pkg/replicas/putter.go:34]: Ah, so THIS is where the redundant put of the root chunk came from?  I was wondering!  Do you mind my asking (for my own education) where the root chunk actually gets put for rlevel==0?

Comment (nugaon) [reply pkg/replicas/putter.go:34]: it is done by the hashtrie module which is in a chunk pipeline process that has a `ChainWrite` function which does the job.

**Review by zelig — APPROVED** [review]

**Review by martinconic — APPROVED** [review]

**Review by acha-bill — APPROVED** [review]
