### PR TITLE
fix: stewardship with erasure encoding

### LINKED ISSUE #4948: erasure coding stewardship endpoint returns false
for erasure encoded data during upload (we tried level 3), the stewardship endpoint returns isRetrievable=false.

The endpoint returns true, however, for the same upload without erasure coding.

### PR DESCRIPTION
**Pull request by acha-bill**
### Checklist

- [ ] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md).
- [ ] My change requires a documentation update, and I have done it.
- [ ] I have added tests to cover my changes.
- [ ] I have filled out the description and linked the related issues.

### Description

When iterating over chunks, parity chunks were incorrectly attempted to be fetched from the redundancy getter, which only supports shards.

### Related Issue (Optional)
closes #4948

### CODE REVIEW

File: pkg/file/joiner/joiner.go [hunk 1]
```diff
@@ -406,6 +406,12 @@ func (j *joiner) processChunkAddresses(ctx context.Context, fn swarm.AddressIter
 			if j.refLength == encryption.ReferenceSize && i < shardCnt {
 				addr = swarm.NewAddress(data[cursor : cursor+swarm.HashSize*2])
 			}
+
+			// not a shard
+			if i >= shardCnt {
```
Comment (istae) [inline pkg/file/joiner/joiner.go:411]: maybe it should be `i >shardCnt` 🤔 
you are also reading `i` from a goroutine, there could be some data race issues here. Pls also check if we are accessing variables here that we should not be without some synchronization mechanism.

**Review by istae — CHANGES_REQUESTED** [review]

File: pkg/file/joiner/joiner.go (hunk 1 above)
Comment (acha-bill) [reply pkg/file/joiner/joiner.go:411]: `i` is 0-indexed. So it should be `i >= shardCnt`
The gourtine that reads `i` has to return before the next iteration. See the waitgroup used below. So there can be no race here.

**Comment by istae** [comment]
Merging this now, a fix for https://github.com/ethersphere/bee/issues/4977 will be included in a different PR
