### PR TITLE
fix: save tags when using chunk/stream

### LINKED ISSUE #4858: Chunks uploaded with websocket are not counted into tag stats
### Context
Bee 2.2.0

### Summary
Uploading chunks with http requests increments the tag `split` value, as it is also incremented uploading with bzz protocol.
Instead uploading using websocket doesn't update it.
Because of this, I suspect that upload with websocket doesn't actual use the tag at all.

### Expected behavior
I should have the same behavior on tag, session and storage uploading with http or uploading with websocket.

### Actual behavior
It seams that uploading with websocket doesn't use tag's session.

### Steps to reproduce
Create a tag, and use it to upload with websocket.
After the upload, try to look at tag status. It has all values to 0, even if chunks have been uploaded.

### PR DESCRIPTION
**Pull request by acha-bill**
### Checklist

- [x] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md).
- [ ] My change requires a documentation update, and I have done it.
- [ ] I have added tests to cover my changes.
- [ ] I have filled out the description and linked the related issues.

### Description

Do not use HTTP request context so that tags will be saved when `putter.Done` is called after the HTTP connection is upgraded to websocket.

### Related Issue (Optional)
closes #4858

### CODE REVIEW

File: pkg/api/chunk_stream.go [hunk 1]
```diff
@@ -56,7 +56,7 @@ func (s *Service) chunkUploadStreamHandler(w http.ResponseWriter, r *http.Reques
 	}
 
 	// if tag not specified use direct upload
-	putter, err := s.newStamperPutter(r.Context(), putterOptions{
+	putter, err := s.newStamperPutter(context.Background(), putterOptions{
```
Comment (martinconic) [inline pkg/api/chunk_stream.go:59]: why is context.Background() better here?

Comment (istae) [reply pkg/api/chunk_stream.go:59]: probably because the go routine below handles the websocket connection but since this function returns, the context is canceled.

Comment (acha-bill) [reply pkg/api/chunk_stream.go:59]: yep

**Review by martinconic — APPROVED** [review]

**Review by istae — APPROVED** [review]
pls add a comment here why this background context is necessary as it's not immediately obvious
