### PR TITLE
fix: cannot get batch after purchase

### LINKED ISSUE #3300: `GET /stamps/<id>` throws `cannot get batch` after purchase
If you query for `GET /stamps/<id>` endpoint with `id` of freshly created stamp it returns `Bad Request: cannot get batch` error.

### PR DESCRIPTION
**Pull request by umerm-work**
### Checklist

- [x] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md).
- [ ] My change requires a documentation update, and I have done it.
- [ ] I have added tests to cover my changes.
- [x] I have filled out the description and linked the related issues.

### Description
Closes #3300

### CODE REVIEW

**Review by istae — APPROVED** [review]
Do we need to update any openapi references with this change, pls confirm,

**Comment by umerm-work** [comment]
> Do we need to update any openapi references with this change, pls confirm,

No, we don't.

File: pkg/api/postage.go [hunk 1]
```diff
@@ -300,10 +301,15 @@ func (s *Service) postageGetStampHandler(w http.ResponseWriter, r *http.Request)
...
-		s.logger.Debug("get stamp issuer: get issuer failed", "batch_id", hex.EncodeToString(id), "error", err)
+	var issuer *postage.StampIssuer
+	for _, stampIssuer := range s.post.StampIssuers() {
+		if bytes.Equal(id, stampIssuer.ID()) {
+			issuer = stampIssuer
+			break
+		}
+	}
+	if issuer == nil {
+		s.logger.Debug("get stamp issuer: get issuer failed", "batch_id", hex.EncodeToString(id), "error")
```
Comment (aloknerurkar) [inline pkg/api/postage.go:312]: There is no error here. Remove the error key.

Also, create a logger here with the API name:
`logger := s.logger.WithName("get_stamp_by_id").Build()`

Then you can remove the `"get stamp issuer:"` from the log message. Check the simplify API PR from peter for examples.

File: pkg/api/postage.go [hunk 2]
```diff
@@ -300,10 +301,15 @@ func (s *Service) postageGetStampHandler(w http.ResponseWriter, r *http.Request)
...
 		s.logger.Error(nil, "get stamp issuer: get issuer failed")
 		jsonhttp.BadRequest(w, "cannot get batch")
```
Comment (aloknerurkar) [inline pkg/api/postage.go:314]: This should be `cannot find batch`. User queries stamp with ID which is not found.

**Review by aloknerurkar — COMMENTED** [review]
Also, once you are done can you post the output of the API in the PR. The JS folks need to confirm this is what is expected before we check in.

File: pkg/api/postage.go (hunk 2 above)
Comment (umerm-work) [reply pkg/api/postage.go]: Done

File: pkg/api/postage.go (hunk 1 above)
Comment (umerm-work) [reply pkg/api/postage.go]: Done

File: pkg/api/postage.go [hunk 3]
```diff
@@ -295,17 +297,22 @@ func (s *Service) postageGetStampHandler(w http.ResponseWriter, r *http.Request)
 	}
 	id, err := hex.DecodeString(idStr)
 	if err != nil {
-		s.logger.Debug("get stamp issuer: decode batch id string failed", "string", idStr, "error", err)
-		s.logger.Error(nil, "get stamp issuer: decode batch id string failed")
-		jsonhttp.BadRequest(w, "invalid batchID")
+		logger.Debug("decode batch id string failed", "string", idStr, "error", err)
+		logger.Error(nil, "decode batch id string failed")
+		jsonhttp.BadRequest(w, "cannot find batch")
```
Comment (aloknerurkar) [inline pkg/api/postage.go:302]: This should be the same as before. This error is for failed parsing.

Comment (umerm-work) [reply pkg/api/postage.go:302]: You mean change it back to `invalid batchID` ?

**Comment by umerm-work** [comment]
First Time
```
{
    "batchID": "52a2733df435ce6c7f1b3891b7afeba630b7deec6000b4aee09daee3b96f7f01",
    "utilization": 0,
    "usable": false,
    "label": "",
    "depth": 20,
    "amount": "600",
    "bucketDepth": 16,
    "blockNumber": 7709035,
    "immutableFlag": false,
    "exists": false,
    "batchTTL": -1,
    "expired": false
}

```
Second Time
```
{
    "batchID": "52a2733df435ce6c7f1b3891b7afeba630b7deec6000b4aee09daee3b96f7f01",
    "utilization": 0,
    "usable": false,
    "label": "",
    "depth": 20,
    "amount": "600",
    "bucketDepth": 16,
    "blockNumber": 7709035,
    "immutableFlag": false,
    "exists": true,
    "batchTTL": -1,
    "expired": false
}
```
Third Time
```
{
    "batchID": "52a2733df435ce6c7f1b3891b7afeba630b7deec6000b4aee09daee3b96f7f01",
    "utilization": 0,
    "usable": true,
    "label": "",
    "depth": 20,
    "amount": "600",
    "bucketDepth": 16,
    "blockNumber": 7709035,
    "immutableFlag": false,
    "exists": true,
    "batchTTL": -1,
    "expired": false
}
```

**Review by mrekucci — APPROVED** [review]

File: pkg/api/postage.go (hunk 3 above)
Comment (aloknerurkar) [reply pkg/api/postage.go:302]: Yes

Comment (aloknerurkar) [inline pkg/api/postage.go:302]: This message was supposed to be renamed. The below message is correct.

Comment (umerm-work) [reply pkg/api/postage.go]: Fixed.

File: pkg/api/postage.go [hunk 4]
```diff
@@ -330,17 +337,15 @@ func (s *Service) postageGetStampHandler(w http.ResponseWriter, r *http.Request)
...
-		resp.Usable = exists && s.post.IssuerUsable(issuer)
-		resp.Label = issuer.Label()
-		resp.Depth = issuer.Depth()
-		resp.Amount = bigint.Wrap(issuer.Amount())
-		resp.BucketDepth = issuer.BucketDepth()
-		resp.BlockNumber = issuer.BlockNumber()
-		resp.ImmutableFlag = issuer.ImmutableFlag()
-		resp.Expired = issuer.Expired()
-	}
+	resp.Utilization = issuer.Utilization()
```
Comment (aloknerurkar) [inline pkg/api/postage.go:340]: This can be moved inside the resp declaration:
```
resp := postageStampResponse {
    // All fields can be initialized here
}
```

Comment (umerm-work) [reply pkg/api/postage.go:340]: Good catch.
