### PR TITLE
fix: remove epoch migration code

### LINKED ISSUE #4540: remove any old localstore rewrite epoch migration logic
* remove any epoch migration code
* remove any old localstore migration steps and code
* remove any old statestore migration steps and code
* any and other remaining old migration code

### PR DESCRIPTION
**Pull request by notanatol**
### Checklist

- [X] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md).

### Description
closes #4540

### CODE REVIEW

File: pkg/statestore/test/store.go [hunk 1]
```diff
@@ -225,5 +225,5 @@ func testStoreIterator(t *testing.T, store storage.StateStorer, prefix string, s
 func testEmpty(t *testing.T, store storage.StateStorer) {
 	t.Helper()
 
-	testStoreIterator(t, store, "", 1) // 1 because of the schema entry.
+	testStoreIterator(t, store, "", 0) // 1 because of the schema entry.
```
Comment (notanatol) [inline pkg/statestore/test/store.go:228]: @istae is this comment still relevant?

do we still have 'schema entry' or was it part of the previous localstore?

Comment (istae) [reply pkg/statestore/test/store.go:228]: this schema entry probably has to do with the empty prefix and the way leveldb is implemented?
maybe @janos can help us here?

Comment (istae) [reply pkg/statestore/test/store.go:228]: which begs the question, how does changing it to `0` continue to work?

Comment (istae) [reply pkg/statestore/test/store.go:228]: looks like we manually insert a `schema` entry to keep a track of the migrations https://github.com/ethersphere/bee/blob/master/pkg/statestore/leveldb/leveldb.go#L176

**Review by istae — APPROVED** [review]

File: pkg/statestore/test/store.go (hunk 1 above)
Comment (janos) [reply pkg/statestore/test/store.go:228]: Yes, that is correct, schema name was inserted under a specific key, but now since putSchemaName is not used, 0 is the correct value. Comment should be removed.

**Review by janos — APPROVED** [review]

**Review by acha-bill — APPROVED** [review]
