### PR TITLE
puller, pullsync: fix outstanding tasks

### LINKED ISSUE #329: pull sync outstanding tasks
this issue enumerates the outstanding issues that arise out of the pull sync initial PR.

- [ ] falling edge kademlia channel wrapper
- [x] metrics
- [x] extract number of bins from pullstorage, pullsync protocol and puller to be injected from constructors
- [x] construct the tests in pullsync and pullstorage around the limit in a way which the limit can be adjusted through the const and that the test adjusts automatically
- [x] puller.go - handle error on next interval L313
- [x] puller.go L390 - eliminate return on top==0 (shouldnt happen, probably related to the mocks) (#810)
- [ ] subscribe pull in localstore - db shutdown might be removable altogether 
- [ ] sync only in NN
- [x] abstract syncCtx to a separate object (#810)
- [ ] get rid of mode set sync pull? just have mode set sync?

related to:
#193 #302 #144 #136 #254

### PR DESCRIPTION
**Pull request by acud**
This PR fixes some of the issues in #329, namely:
- removal of the `top==0` in puller implementation. this was necessary due to incorrect behavior of the mock, which should have returned a context cancelled error, but instead just returned.
- moving some of the functionality related to sync context to the `syncPeer` object. it is a question whether this type needs to be exposed in a different package.
- some small cleanups and DRYing of the existing logic

closes #329 as rest of tasks have discrete issues now

### CODE REVIEW

**Comment by Eknir** [comment]
Would appreciate a PR description :)

**Comment by acud** [comment]
@Eknir once the PR is no longer `in progress`.... patience

**Review by janos — APPROVED** [review]
Looks good.

File: pkg/puller/puller.go [hunk 1]
```diff
@@ -330,34 +289,28 @@ func (p *Puller) syncPeer(ctx context.Context, peer swarm.Address, po, d uint8)
...
-		binCtx, cancel := context.WithCancel(ctx)
-		syncCtx.binCancelFuncs[po] = cancel
-		if cur > 0 {
-			p.wg.Add(1)
-			go p.histSyncWorker(binCtx, peer, bin, cur) // start historical
-		}
-		p.wg.Add(1)
-		go p.liveSyncWorker(binCtx, peer, bin, cur) // start live
-
+		p.syncPeerBin(ctx, syncCtx, peer, po, c[po])
```
Comment (zelig) [inline pkg/puller/puller.go:292]: do not sync outside NN pretty please. this could be a (debug) API call used when. a node wants to quickly fill a. lot of storage beside what is currently. its neighbourhood.

Comment (acud) [reply pkg/puller/puller.go:292]: i split this to a separate issue (#818) because this PR already changes some things in pull sync and this would be a big changeset to test in one go. i'd be happy to have it in a separate pr, with separate testing, to see that there are no regressions

**Review by zelig — APPROVED** [review]
