### PR TITLE
fix: exclude expired stamps unless queried 

### LINKED ISSUE #3095: Don't return expired stamps in `/stamps`
⚠️ Requests for support in an issue-format will be closed immediately. For support questions, we welcome you to our [Discord](https://discord.gg/XGNBEKktkD).

# Task

We currently show all batches when querying the `/stamps` endpoint. We should exclude them from the response (i.e. the response should always show only the existing, non-expired stamps), but also add the possibility to show them upon need, by adding a querystring parameter that would allow a requester to display all (including expired) stamps, like `/stamps?all=true` or `/stamps?debug=true`

## Acceptance criterea

- expired stamps _should not_ be displayed when querying the `/stamps` endpoint
- expired stamps _should_ be displayed when querying the `/stamps?all=true` endpoint

### PR DESCRIPTION
**Pull request by swarmHaseeb**
### Checklist

- [x] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md)
- [x] My change requires a documentation update and I have done it
- [x] I have added tests to cover my changes.

### Description

This PR fixes #3095 assigned on July 19th 2022.
### Screenshots (if appropriate):

---
This change is [Reviewable](https://reviewable.io/reviews/ethersphere/bee/3097)

### CODE REVIEW

**Review by notanatol — APPROVED** [review]

File: pkg/api/postage_test.go [hunk 1]
```diff
@@ -232,6 +232,48 @@ func TestPostageGetStamps(t *testing.T) {
 	})
 }
 
+func TestPostageGetNonExistingStamps(t *testing.T) {
+	ts, _, _, _ := newTestServer(t, testServerOptions{DebugAPI: true, Post: nil, BatchStore: nil, BlockTime: nil})
```
Comment (istae) [inline pkg/api/postage_test.go:236]: here you need to pass in a `mockpost`  and a nil batchstore so that the stamp issuer returns an issuer but no batch is returned from the batchstore.

**Review by istae — CHANGES_REQUESTED** [review]

**Review by swarmHaseeb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/3097)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @istae and @swarmHaseeb)

___
*[`pkg/api/postage_test.go` line 236 at r1](https://reviewable.io/reviews/ethersphere/bee/3097#-N7LbjTQtDyItbE8jlUg-r1-236:-N7LoR0L9de0BOyzm0LZ:bnu32a0) ([raw file](https://github.com/ethersphere/bee/blob/8743abc872103de3faab5d87f6dee61cc9e8f6d7/pkg/api/postage_test.go#L236)):*
<details><summary><i>Previously, istae (istae) wrote…</i></summary><blockquote>

here you need to pass in a `mockpost`  and a nil batchstore so that the stamp issuer returns an issuer but no batch is returned from the batchstore.  
</blockquote></details>

this change has been implemented in latest commit. Waiting for your approval.

File: pkg/api/postage_test.go [hunk 2]
```diff
@@ -232,6 +232,51 @@ func TestPostageGetStamps(t *testing.T) {
 	})
 }
 
+func TestPostageGetNonExistingStamps(t *testing.T) {
```
Comment (aloknerurkar) [inline pkg/api/postage_test.go:235]: This test is wrong. You are not creating a stampIssuer here, so there is nothing to iterate over. Also the name of this test is doesnt make sense.

It would be better to have just 1 test and have 2 subtests as in both the tests you are doing the same thing.

File: pkg/api/postage_test.go [hunk 3]
```diff
@@ -232,6 +232,51 @@ func TestPostageGetStamps(t *testing.T) {
...
+	ts, _, _, _ := newTestServer(t, testServerOptions{DebugAPI: true, Post: mp, BatchStore: nil, BlockTime: big.NewInt(2)})
+
+	t.Run("expired stamp", func(t *testing.T) {
+		jsonhttptest.Request(t, ts, http.MethodGet, "/stamps", http.StatusOK,
+			jsonhttptest.WithExpectedJSONResponse(&api.PostageStampsResponse{Stamps: []api.PostageStampResponse{}}),
+		)
+	})
+}
+
+func TestPostageGetAllStamps(t *testing.T) {
```
Comment (aloknerurkar) [inline pkg/api/postage_test.go:248]: You could have just 1 test which has 2 subtests. In one case you can pass the `all=true` param and other case will not pass it.

It would be better to have multiple stamps as well. Maybe 1 valid and 1 expired stamp. If you need to modify some of the mock classes for this, that should not be a problem. Mock classes are meant for tests, so if they dont cover certain things we can always add them.

**Review by aloknerurkar — CHANGES_REQUESTED** [review]

**Review by swarmHaseeb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/3097)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @aloknerurkar and @istae)

___
*[`pkg/api/postage.go` line 181 at r1](https://reviewable.io/reviews/ethersphere/bee/3097#-N7LjJcN0-EcDQDTmQRn:-N7UAIMMDJA7UMsluheR:bfhjkd4) ([raw file](https://github.com/ethersphere/bee/blob/8743abc872103de3faab5d87f6dee61cc9e8f6d7/pkg/api/postage.go#L181)):*
<details><summary><i>Previously, swarmHaseeb (Haseeb Raja) wrote…</i></summary><blockquote>

Maybe, if suggested, we can also add a condition to check for non-expired TTL.
</blockquote></details>

isDebug is changed to isAll
___
*[`pkg/api/postage.go` line 19 at r2](https://reviewable.io/reviews/ethersphere/bee/3097#-N7LbjTQtDyItbE8jlUf-r2-19:-N7U9Sbs7ejeFiBHt4oK:btt9bxm) ([raw file](https://github.com/ethersphere/bee/blob/5cfb99b9c4a3ade5b23c3c1ed4093456f5d02d7f/pkg/api/postage.go#L19)):*
<details><summary><i>Previously, aloknerurkar wrote…</i></summary><blockquote>

Are you not using gofmt? All the standard packages need to be at the top of the import list. Followed by a line break and then all the imported/local packages.

This needs to be reverted and also your IDE probably needs to be fixed. We have a [style guide](https://github.com/ethersphere/bee/blob/master/CODINGSTYLE.md). If in doubt, look at other code files and try to maintain all the standards.
</blockquote></details>

Done. I don't know why but Goland, even though I have enabled gofmt, does not actually sort imports according to that. Trying to fix it alternatively.
___
*[`pkg/api/postage.go` line 163 at r2](https://reviewable.io/reviews/ethersphere/bee/3097#-N7LbjTQtDyItbE8jlUf-r2-163:-N7U9ThSEqVfd3R88Kxx:b-669fsu) ([raw file](https://github.com/ethersphere/bee/blob/5cfb99b9c4a3ade5b23c3c1ed4093456f5d02d7f/pkg/api/postage.go#L163)):*
<details><summary><i>Previously, aloknerurkar wrote…</i></summary><blockquote>

`isDebug` doesnt seem to be right name for this. This can be used for normal cases as well. A name which describes what it does seems to be better.
</blockquote></details>

Done. Please suggest if another change is required.
___
*[`pkg/api/postage_test.go` line 235 at r2](https://reviewable.io/reviews/ethersphere/bee/3097#-N7LbjTQtDyItbE8jlUg-r2-235:-N7UAO9oCOvJN-ySPlom:b23asms) ([raw file](https://github.com/ethersphere/bee/blob/5cfb99b9c4a3ade5b23c3c1ed4093456f5d02d7f/pkg/api/postage_test.go#L235)):*
<details><summary><i>Previously, aloknerurkar wrote…</i></summary><blockquote>

This test is wrong. You are not creating a stampIssuer here, so there is nothing to iterate over. Also the name of this test is doesnt make sense.

It would be better to have just 1 test and have 2 subtests as in both the tests you are doing the same thing.
</blockquote></details>

Test cases changed accordingly. Please let me know if this is ok now.
@istae Thank you for your help.    
___
*[`pkg/api/postage_test.go` line 248 at r2](https://reviewable.io/reviews/ethersphere/bee/3097#-N7LbjTQtDyItbE8jlUg-r2-248:-N7UAePA6Pp-uiNq1aY9:b7n641c) ([raw file](https://github.com/ethersphere/bee/blob/5cfb99b9c4a3ade5b23c3c1ed4093456f5d02d7f/pkg/api/postage_test.go#L248)):*
<details><summary><i>Previously, aloknerurkar wrote…</i></summary><blockquote>

You could have just 1 test which has 2 subtests. In one case you can pass the `all=true` param and other case will not pass it.

It would be better to have multiple stamps as well. Maybe 1 valid and 1 expired stamp. If you need to modify some of the mock classes for this, that should not be a problem. Mock classes are meant for tests, so if they dont cover certain things we can always add them.
</blockquote></details>

Test Cases modified accordingly.

File: pkg/api/postage_test.go [hunk 4]
```diff
@@ -208,6 +208,8 @@ func TestPostageGetStamps(t *testing.T) {
 	cs := &postage.ChainState{Block: 10, TotalAmount: big.NewInt(5), CurrentPrice: big.NewInt(2)}
 	bs := mock.New(mock.WithChainState(cs), mock.WithBatch(b))
 	ts, _, _, _ := newTestServer(t, testServerOptions{DebugAPI: true, Post: mp, BatchStore: bs, BlockTime: big.NewInt(2)})
+	bsForNonExistingStamp := mock.New(mock.WithChainState(cs))
+	tsForNonExistingStamp, _, _, _ := newTestServer(t, testServerOptions{DebugAPI: true, Post: mp, BatchStore: bsForNonExistingStamp, BlockTime: big.NewInt(2)})
```
Comment (aloknerurkar) [inline pkg/api/postage_test.go:212]: This test is still not correct. We dont use multiple servers for the same test. Secondly, your All stamps test is not different from the single stamp test case. I think its important to understand what you actually want to test before writing the tests.

The thing we NEED to test is that the handler returns only valid stamps (i.e. stamps are are not expired) in normal case and all stamps (even the expired ones) using the argument. So you should have 2 batches, one of them should be expired and one of them should be valid. This way you can query the same server with and without the arguments and be sure that your logic is correct. Current test looks like a hack to get it working.

Comment (swarmHaseeb) [reply pkg/api/postage_test.go:212]: Thank you, lemme fix it, got it now.

**Review by aloknerurkar — APPROVED** [review]

**Review by mrekucci — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/3097)* status: all files reviewed, 7 unresolved discussions (waiting on @aloknerurkar and @istae)

**Review by istae — APPROVED** [review]

**Review by mrekucci — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/3097)* status: 4 of 5 files reviewed, 10 unresolved discussions (waiting on @aloknerurkar, @istae, and @swarmHaseeb)

___
*[`openapi/Swarm.yaml` line 1694 at r5](https://reviewable.io/reviews/ethersphere/bee/3097#-N7uU35F3vSZMq4OZKeW:-N7uU35F3vSZMq4OZKeX:bhai5ds) ([raw file](https://github.com/ethersphere/bee/blob/c07801093efb16c9d9066386b5c42ca27ee4234b/openapi/Swarm.yaml#L1694)):*
> ```YAML
>           description: Default response
> 
>   "/stamps?all=true":
> ```

The query parameter should be described in the [`parameters`](https://swagger.io/docs/specification/describing-parameters/#query-parameters) section of the `/stamps` path.
___
*[`openapi/SwarmDebug.yaml` line 812 at r5](https://reviewable.io/reviews/ethersphere/bee/3097#-N7uUmLF-PXDPEK5_tbM:-N7uUmLGCFgDmJLI0VCw:bf26u1) ([raw file](https://github.com/ethersphere/bee/blob/c07801093efb16c9d9066386b5c42ca27ee4234b/openapi/SwarmDebug.yaml#L812)):*
> ```YAML
>           description: Default response
> 
>   "/stamps?all=true":
> ```

The same as above.

**Review by swarmHaseeb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/3097)* status: 3 of 6 files reviewed, 10 unresolved discussions (waiting on @aloknerurkar, @istae, and @mrekucci)

___
*[`openapi/Swarm.yaml` line 1694 at r5](https://reviewable.io/reviews/ethersphere/bee/3097#-N7uU35F3vSZMq4OZKeW:-N7ymYRTCaCgHLB1HDav:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/c07801093efb16c9d9066386b5c42ca27ee4234b/openapi/Swarm.yaml#L1694)):*
<details><summary><i>Previously, mrekucci wrote…</i></summary><blockquote>

The query parameter should be described in the [`parameters`](https://swagger.io/docs/specification/describing-parameters/#query-parameters) section of the `/stamps` path.
</blockquote></details>

Done.
___
*[`openapi/SwarmDebug.yaml` line 812 at r5](https://reviewable.io/reviews/ethersphere/bee/3097#-N7uUmLF-PXDPEK5_tbM:-N7ymZkLDJ-O48A1wUhe:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/c07801093efb16c9d9066386b5c42ca27ee4234b/openapi/SwarmDebug.yaml#L812)):*
<details><summary><i>Previously, mrekucci wrote…</i></summary><blockquote>

The same as above.
</blockquote></details>

Done.
___
*[`pkg/api/postage_test.go` line 236 at r2](https://reviewable.io/reviews/ethersphere/bee/3097#-N7LbjTQtDyItbE8jlUg-r2-236:-N7yma4yE1QD4YVJ1khf:b-896fix) ([raw file](https://github.com/ethersphere/bee/blob/5cfb99b9c4a3ade5b23c3c1ed4093456f5d02d7f/pkg/api/postage_test.go#L236)):*
<details><summary><i>Previously, istae (istae) wrote…</i></summary><blockquote>

remove b
</blockquote></details>

Done.

**Review by mrekucci — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ethersphere/bee/3097)* status: all files reviewed, 8 unresolved discussions (waiting on @aloknerurkar and @istae)

**Review by istae — APPROVED** [review]

**Comment by significance** [comment]
🔥
